#!/bin/sh

YACM_BASE_DIR=;
YACM_DIR=;

function main() {
  # Capture full command, for passing to hooks
  # the parameters will be space delimited and
  # spaces, tabs, and backslashes will be escaped
  _tab=$'\t'
  for param in "$@"; do
    param="${param//\\/\\\\}"
    param="${param//$_tab/\\$_tab}"
    param="${param// /\\ }"
    _fc+=( "$param" )
  done
  FULL_COMMAND="${_fc[*]}"

  # Create the YACM_DIR & YACM_DATA if they doesn't exist yet
  [ -d "$YACM_BASE_DIR" ] || mkdir -p "$YACM_BASE_DIR"
  [ -d "$YACM_DIR" ] || mkdir -p "$YACM_DIR"

  local retval=0
  internal_commands="^(bootstrap|help|--help|init|version|--version)$"

  if [ -z "$1" ] ; then
    # No argumnts will result in help()
    help;
  elif [[ "$1" =~ $internal_commands ]]; then
    # For internal commands, process all of the arguments
    YADM_COMMAND="${1//-/_}";
    YADM_COMMAND="${YADM_COMMAND/__/}";
    YADM_ARGS=();
    shift;

  else
    # Invalid command, throw error and run help menu
    echo "It appears you have entered an invalid command!";
    help
  fi    
}

function set_global_args() {
  # global arguments are removed before the main processing is done
  MAIN_ARGS=()
  while [[ $# -gt 0 ]] ; do
    key="$1"
    case $key in
      -Y|--yadm-dir) # override the standard YADM_DIR
        YADM_DIR="$(qualify_path "$2" "yadm")"
        shift
      ;;
      --yadm-base-dir) # override the standard YADM_BASE_DIR
        YADM_BASE_DIR="$(qualify_path "$2" "data")"
        shift
      ;;
      *) # main arguments are kept intact
        MAIN_ARGS+=("$1")
      ;;
    esac
    shift
  done
}

function help() {

  local msg
  IFS='' read -r -d '' msg << EOF
Usage: yacm <command> [options...]

Bob Blahlaw
EOF
  printf '%s\n' "$msg"
}

function set_yacm_defaults() {
  # only set YACM_BASE_DIR if it hasn't already be set
  if [ -z $YACM_BASE_DIR ]; then
    local base_yacm_dir="${XDG_CONFIG_DIR:-$HOME/.config}";
    YACM_BASE_DIR="${base_yacm_dir}";
  fi

  # only set YACM_DIR if it hasn't already be set
  if [ -z $YACM_DIR ]; then
    YACM_DIR="${YACM_BASE_DIR}/yacm";
  fi
}

set_global_args "$@";
set_yacm_defaults;
main "${MAIN_ARGS[@]}";
