name: ShellCheck yacm

on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: test
          severity: warning
