name: Test yacm

on: push

jobs:
  test-systemd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run systemd tests
        run: TEST=systemd make run-system-tests

  test-runit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run runit test
        run: TEST=runit make run-system-tests

  test-apt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run apt tests
        run: TEST=apt make run-system-tests

  test-dnf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run dnf tests
        run: TEST=dnf make run-system-tests

  test-pacman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run pacman tests
        run: TEST=pacman make run-system-tests

  test-paru:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run paru tests
        run: TEST=paru make run-system-tests

  test-yay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run yay tests
        run: TEST=yay make run-system-tests

  test-yum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run yum tests
        run: TEST=yum make run-system-tests
