name: Test yacm

on:
  push:
    branches:
      - actions-test

jobs:
  test-systemd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run systemd tests
        run: cd test/systemd && ./run-tests.sh

  test-runit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run runit test
        run: make test-runit

  test-apt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run apt tests
        run: make test-apt

  test-pacman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run pacman tests
        run: make test-pacman

  test-paru:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run paru tests
        run: make test-paru
