name: Test yacm

on:
  push:
    branches:
      - actions-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: cd to test directory
        run: cd test/ubuntu

      - name: run tests
        run: ./run-test.sh
